### ISSUE TITLE
`sdl3-sys` bindings incompatible with current code

### ISSUE THREAD

**Issue by jgcodes2020** [revmischa/sdl3-rs#16]
Latest commit which bumped sdl3-sys version breaks *everything*. It appears that the generator has gone through some major overhauls since you last updated it.

**Comment by revmischa** [comment]
Yep that is correct!

**Comment by revmischa** [comment]
I'm updating some of them now, pushing changes, help is always appreciated!

**Comment by revmischa** [comment]
more updates: https://github.com/revmischa/sdl3-rs/pull/18

**Comment by Lokathor** [comment]
I suspect the fact that the latest commit isn't published to crates.io would be enough evidence that it's not fully ready to be used by outsiders ;3

**Comment by maia-s** [comment]
Yes, and `sdl3-sys 0.0.10` isn't fully stable yet either. I've reviewed the generated bindings over the past few days and made corrections to fix types that were inferred wrong by the generator, and a few things that were incorrectly skipped. I think I've fixed almost all of it now, but people using `sdl3-sys` and reporting back about any issues they have would help :)

I think the biggest change since `0.0.10` is that string constants are now type `*const c_char` instead of `&CStr`, because almost all the strings are hints or properties that are passed as-is as arguments to SDL functions, and Rust is planning to remove the stored length from `&CStr` anyway.

**Comment by revmischa** [comment]
@maia-s I'll probably have more questions, but one I ran into yesterday: do you happen to know what happened to `SDL_GetMasksForPixelFormatEnum` and `SDL_GetPixelFormatEnumForMasks`?
They seem to have vanished as far as I can tell

**Comment by maia-s** [comment]
Yes, they were renamed to `SDL_GetMasksForPixelFormat` and `SDL_GetPixelFormatForMasks`!

You can find all the renamed symbols compared to SDL 2 in [`SDL_oldnames.h` in the SDL repo](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_oldnames.h). The previous names you used aren't in there, so ig they were renamed more than once during SDL 3 development. There shouldn't be more renames now that it's abi stable though.

**Comment by maia-s** [comment]
https://docs.rs/sdl3-sys/ is a nice way to browse the api now too :D

**Comment by revmischa** [comment]
I finally got it to build again! Just published 0.9.0 https://crates.io/crates/sdl3
I'm sure many many things are broken, the examples need updating, tests need fixing, docs need updating, etc. I took a stab at supporting the new audio API but that file needs a fair bit of cleanup.

But at least now we can start actually trying to use it again!
